### ISSUE TITLE
How to Disable Delete Option in ContextMenu

### ISSUE THREAD

**Issue by AmitAjmera** [Yalantis/Context-Menu.iOS#11]
Another Issue I am facing is that I got two tableview in single screen,One is Context Menu and Other is of my Application, Now I am using "commitEditingStyle" to delete Table cell item by Swipe in my Application table but This Feature will obviously look odd when any user do swipe in ContextMenu so how to disable it for our ContextMenu Table.
![ios simulator screen shot apr 19 2015 10 14 03 pm](https://cloud.githubusercontent.com/assets/11287210/7220387/9406a5ec-e6e2-11e4-9e28-f6bf091728ec.png)

**Comment by maksTheAwesome** [comment]
Hello Amit. Thank you for your interest to our component. Regarding your issue did you try turning YES for your table view only for "canEditRowAtIndexPath" like in the sample below:

``` objective-c
- (BOOL)tableView:(UITableView *)tableView canEditRowAtIndexPath:(NSIndexPath *)indexPath {
       if (tableView == myAppTableView) {
          return YES;
       } else {
         return NO;
       }
}
```

Please try the solution and let me know if I can close the issue.

**Comment by AmitAjmera** [comment]
Oh Great!! I was not aware about this method and It worked for me fine and Yes,You can close this issue.

Thanks again :)

**Comment by maksTheAwesome** [comment]
Perfect! Have fun with your project!
