### ISSUE TITLE
how can i code the menu table to be displayed in middle  right of the view?

### ISSUE THREAD

**Issue by JJJJJJJerk** [Yalantis/Context-Menu.iOS#12]
by the way i love Yalantis’s code. god bless Ukraine ,defeat the devil of Russia and his bastard son Chinese Communist Party.

**Comment by chocolatemetoprolol** [comment]
set   UIEdgeInsets inserts;
[self.contextMenuTableView showInView:self.navigationController.view withEdgeInsets:inserts animated:YES];
UIView+YALConstraints.h
- (void)addSubViewiew:(UIView *)view withSidesConstrainsInsets:(UIEdgeInsets)insets
  {
  code....
  }
