### ISSUE TITLE
crash when i display the menu

### ISSUE THREAD

**Issue by mjasa** [Yalantis/Context-Menu.iOS#13]
when i press the button to show menu and scrolling the table until the animating cells disappear from screen

the error in YALContextMenuTableView.m line 164

 **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayI objectAtIndex:]: index 9 beyond bounds [0 .. 7]'

**Comment by SalvaP** [comment]
same issue to me

**Comment by PasqualePuzio** [comment]
Same issue here. Hope it'll be fixed soon.
