### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by JayachandraA** [Yalantis/Context-Menu.iOS#14]
I want to use [Sourcegraph](https://sourcegraph.com) for Context-Menu.iOS code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/Yalantis/Context-Menu.iOS. (It should only take 30 seconds.)

Thank you!

**Comment by maksym-letiushov** [comment]
Hi
Sourcegraph currently doesn't support Objective-C language.
Please find this issue https://github.com/sourcegraph/sourcegraph.com/issues/26
When they support it we can back to this issue, but now even if we enable sourcegraph you won't have possibility to search, browse and see usage examples. So, let's back to this later.
Thank you.
