### ISSUE TITLE
Constraints conflict when implementing into tableviewcontroller

### ISSUE THREAD

**Issue by khalilleo** [Yalantis/Context-Menu.iOS#16]
Got this problem when implementing contect-menu into my exsiting tableviewcontroller:

http://pastebin.com/4Vfes3Tv

The menu won't show at all

However it works fine on normal UIViewController, any idea how to fix this?

Thanks for your time and awsome project!

**Comment by EgorSobko** [comment]
@khalilleo Hi, thanks for using Context-Menu. I suppose, that you assign 'self' in this method in UITableViewController: [[YALContextMenuTableView alloc] initWithTableViewDelegateDataSource:self]. But your existing tableViewController has it's own flow for cells. Please, provide us with more code, especially when you initialize YALContextMenuTableView. I suggest you to make a new object that will provide logic for YALContextMenuTableView and assign it when you initialize latter.

**Comment by khalilleo** [comment]
Thanks for the reply!

**Comment by rockia** [comment]
Here is how I fixed this issue.
I tagged my non-context-menu tableview as 1 and for set appropriate tableview datasource accordingly.

```
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    if (tableView.tag == 1) {
        return [mainList count];
    }
    else{
        return [contextMenuList count];
    }
}


- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {

    if (tableView.tag == 1) {
        UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"yourCell" forIndexPath:indexPath];
        return cell;
    }

    // Context Menu
    else{
        ContextMenuCell *cell = [tableView dequeueReusableCellWithIdentifier:menuCellIdentifier
                                                                forIndexPath:indexPath];

        if (cell) {
            // Set your contentmenu cell
        }

        return cell;
    }
}
```
