### ISSUE TITLE
Cocoapods no longer working

### ISSUE THREAD

**Issue by pjebs** [Yalantis/Context-Menu.iOS#17]
This worked perfectly via cocoapods until today.

Now it says:

Analyzing dependencies
[!] Unable to satisfy the following requirements:
- `ContextMenu.iOS (~> 1.0.0)` required by `Podfile`

**Comment by PasqualePuzio** [comment]
I have the same issue

**Comment by liloew** [comment]
This influence me also

**Comment by faoiseamh** [comment]
Same here

**Comment by weinanfeng** [comment]
Same +1

**Comment by Art3mS1d** [comment]
Hmm, can't reproduce. Can you provide more information? What `pod --version` and xcode version you use?

**Comment by weinanfeng** [comment]
I fixed it by specifying the platform version IOS 8.

**Comment by EgorSobko** [comment]
Hi all, I'm using cocoapods 0.39.0 and I couldn't reproduce this problem. Please try to update cocoapods and if this problem still occurs do not hesitate to contact us.
