### ISSUE TITLE
Swift problem

### ISSUE THREAD

**Issue by mpnguyenreply** [Yalantis/Context-Menu.iOS#18]
Hi guys, 

I'm trying to integrate context-menu-ios to my Swift-project. Basically I used Cocoapods to integrate the framework. I have the same codebasis like the context-menu.ios example, but I get an error: 

"ViewController.swift:113:10: Objective-C method 'tableView:didSelectRowAtIndexPath:' provided by method 'tableView(_:didSelectRowAtIndexPath:)' conflicts with optional requirement method 'tableView(_:didSelectRowAtIndexPath:)' in protocol 'UITableViewDelegate'"

My code looks like this: 

func tableView(tableView: YALContextMenuTableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        tableView.dismisWithIndexPath(indexPath)
    }

The same code in objective-c does not handle an error.
Does anybody have a solution for this issue?

thx

**Comment by EgorSobko** [comment]
@mpnguyenreply Hi, thanks for using.
Please, try to do this:
 func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        let yalTableView = tableView as! YALContextMenuTableView
        yalTableView.dismisWithIndexPath(indexPath)
    }
