### ISSUE TITLE
Cannot find an initializer for type in Swift

### ISSUE THREAD

**Issue by sanarroya** [Yalantis/Context-Menu.iOS#19]
Hi Im using Context-Menu.iOS in my swift proyect but i get an error when i try to initialize it:

let contextMenuTableView  = YALContextMenuTableView(tableViewDelegateDataSource: self)

and the error message:

Cannot find an initializer for type 'YALContextMenuTableView' that accepts an argument list of type '(tableViewDelegateDataSource: ImageEditing -> () -> ImageEditing)'

Thanks

**Comment by EgorSobko** [comment]
@sanarroya Hi, please make sure you have implemented all protocols for delegateDataSource object

**Comment by maksym-letiushov** [comment]
delegateDataSource must conform to UITableViewDelegate and UITableViewDataSource protocols
