### ISSUE TITLE
How to display it from left instead of right ? 

### ISSUE THREAD

**Issue by cdeust** [Yalantis/Context-Menu.iOS#21]
I'm trying to make the context menu coming from left instead of coming from right.

**Comment by emiliomarin** [comment]
Did you get it to work on the left?

**Comment by emiliomarin** [comment]
Hi, all you have to do is go to the ContextMenuCell.xib and put the image in the left side and the label in the right one. Then you have to select the label and change the text alignment

**Comment by maksym-letiushov** [comment]
@cdeust , @emiliomarin you can change layout in the xib, but currently menu opens from left to right and closes from right to left. We are going to add both directions in the nearest future. Thank you for issue.
