### ISSUE TITLE
Cocoapods no longer working

### ISSUE THREAD

**Issue by Vernsu** [Yalantis/Context-Menu.iOS#30]
cocoapods 0.39.0 

[!] Unable to satisfy the following requirements:
- `ContextMenu.iOS (~> 1.1.0)` required by `Podfile`

Specs satisfying the `ContextMenu.iOS (~> 1.1.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by EgorSobko** [comment]
@Vernsu Hi, check your project's minimum deployment target. It should be at least 7.1. If you'll meet this kind of trouble in future, feel free to contact us.
