### ISSUE TITLE
Swift Update

### ISSUE THREAD

**Issue by SketchySwift** [Yalantis/Context-Menu.iOS#33]
Please update this one to swift. I really want it but it's in objective-c :(

**Comment by pjebs** [comment]
??? You can easily use it from Swift

**Comment by SketchySwift** [comment]
How?

**Comment by pjebs** [comment]
You need to create a bridging header. If you google Xcode mixed project you can find out how to use obj c code from swift. It's very easy

**Comment by SketchySwift** [comment]
ok but how do I use it with swift after I have the bridging header setup and all that stuff?

**Comment by SketchySwift** [comment]
I have all the pod's installed and the bridging header. Now how do I use the framework with swift?

**Comment by KaterynaZaikina** [comment]
@HardcoreIOS answered https://github.com/Yalantis/Context-Menu.iOS/issues/34

**Comment by HardcoreIOS** [comment]
How come you are closing everything?
