### ISSUE TITLE
Usage with swift

### ISSUE THREAD

**Issue by SketchySwift** [Yalantis/Context-Menu.iOS#34]
How can I use it with swift? I have the bridging header and pod installed but don't know how to use it now with swift, please help!

**Comment by KaterynaZaikina** [comment]
@HardcoreIOS, you can easily use it in swift without creating a bridging header (it will be made automatically), just add  a line: use_frameworks! to your podfile and use Context-Menu with swift syntax.

**Comment by SketchySwift** [comment]
No, my question is, what is the code. All the steps are written in objective-c. I already have the briding header, pod installed etc... and all that stuff. How do I follow the steps to create the menu ? they are in objective-c :(

**Comment by KaterynaZaikina** [comment]
Write 'import ContextMenu_iOS' in your ViewController.swift, then go into ContextMenu_iOS (cmd+tap), choose what you need (UIView_YALConstraints, YALContextMenuCell, YALContextMenuTableView) and look for any swift code you need. Enjoy swift :)

**Comment by SketchySwift** [comment]
Have you used it? Could you please give me your full code on how you used it

**Comment by HardcoreIOS** [comment]
?

**Comment by KaterynaZaikina** [comment]
Unfortunately, I don't have a full code snippet to share, but you can follow steps I wrote before, also visit https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-ID35 and according to guidelines in READ.ME you can write code in swift.

**Comment by HardcoreIOS** [comment]
Ok Thanks

**Comment by SketchySwift** [comment]
@PravdaEvgen Can you please add how to use it with swift in the doc?

**Comment by SketchySwift** [comment]
I still don't understand how to use it with swift

**Comment by SketchySwift** [comment]
@PravdaEvgen Why did you close the issue?

**Comment by felipecaldas** [comment]
Follow this link: https://github.com/tarek360/Objective-C-ContextMenu-in-Swift
It's awesome :)

**Comment by serejahh** [comment]
Hi @HardcoreIOS. I've updated readme with swift usage
