### ISSUE TITLE
Best way is to add the view in the UIWindow

### ISSUE THREAD

**Issue by fu-xianfeng** [Yalantis/Context-Menu.iOS#35]
When i user it, i found your demo is to hide the statusBar at the very beginning, i think it is not good. My solution is to add the view in the main window, and make the windowLevel high than the statusbar window level: `kWindow.windowLevel = UIWindowLevelStatusBar + 1; contextMenuTableView.showInView(kWindow, withEdgeInsets: UIEdgeInsetsZero, animated: true)`. When hide the view: `kWindow.windowLevel = originalWindowLevel`

**Comment by greynguyen** [comment]
@fu-xianfeng Can you elaborate more on what you did when you show the contextMenuTableView. I was able to bring the window level up, but that consequently removes the status bar from my view as well. Is there a way to keep the status bar but push the contextMenuTableView above it? Thanks!

**Comment by serejahh** [comment]
Hi @ndduong97. As I mentioned in #36. It should be implemented via custom modal presentation style to present over status bar
