### ISSUE TITLE
Top Bottom - The first item is right at the battery indicator

### ISSUE THREAD

**Issue by felipecaldas** [Yalantis/Context-Menu.iOS#36]
Hi all,

Thanks for this awesome library.
I just started using it today and got pretty much everything setup.

The problem is that the first cell of my menu is right on top of the battery indicator. What can I do to fix this?

![simulator screen shot 28 jul 2016 10 34 32 pm](https://cloud.githubusercontent.com/assets/3864696/17212515/1de140de-5513-11e6-8f38-82be03ca16b6.png)

**Comment by serejahh** [comment]
Hi @felipecaldas. Thanks for your interest to our component!

You have two options:
1. Show/hide status
2. Play with windowLevel
Both options should be handled when the menu appears/dissapears

I suppose, it'd be better to implement the component via custom view controller with modal presenting.
