### ISSUE TITLE
Does not work on iPad

### ISSUE THREAD

**Issue by andresteves** [Yalantis/Context-Menu.iOS#5]
Menu cover the entire width and half the screen with white color and other half with semi transparent black color. Anyone have an idea how to solve this?

**Comment by maksym-letiushov** [comment]
Thank you. We will take a look.

**Comment by kolorobos** [comment]
I cannot reproduce the bug.
Can you please specify the steps or share some code?

**Comment by andresteves** [comment]
Sure, the steps i took was basically set the app as "Universal" on project settings in general tab and ran it.

![ios simulator screen shot 16 mar 2015 16 14 28](https://cloud.githubusercontent.com/assets/645072/6670633/b61ad05a-cbf7-11e4-9fed-71448f5e31e7.png)

**Comment by kolorobos** [comment]
Thank you, I will check it tomorrow and answer you ASAP

**Comment by andresteves** [comment]
Thanks

**Comment by maksym-letiushov** [comment]
Thank you
