### ISSUE TITLE
Background view not set fit to screen in iPad 

### ISSUE THREAD

**Issue by AmitAjmera** [Yalantis/Context-Menu.iOS#7]
I have integrated this menu in my App. Its working fine in all iPhone but while using in iPad,If you tap on menu then Background of this menu not set fit to screen.

**Comment by maksTheAwesome** [comment]
We used to fix the issue and updated the component with commit about 2 days ago:
https://github.com/Yalantis/Context-Menu.iOS/commit/bc7b5587eda66d6e0f0234ec28d8a546cf607c2d
Please make sure you use the most updated component version. Also you are welcome to use the CocoaPods now to to keep the component updated.

Please let me know if I can close the issue now.

**Comment by AmitAjmera** [comment]
Ohh...Just one line code was harassing me (of updated version).Issue got solved now and working on all iPhone and iPad properly. Thank you very much for your support and Yes, You can close this issue.

**Comment by maksTheAwesome** [comment]
Thank you. And have fun with the component.
